language: go

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...
  - language: python
    python: "3.6"
    script:
      - pip install pipenv
      - cd clients/py
      - pipenv sync --dev
      - pipenv run python -m pytest -v
  - language: python
    python: "3.7-dev"
    script:
      - pip install pipenv
      - cd clients/py
      - pipenv sync --dev
      - pipenv run python -m pytest -v

env:
  - GO111MODULE=on

install: true
