verbose = "info"

[[backends]]
name = "v3io"
type = "kv"
v3ioUrl = "http://v3.io"
container = "a"
path = "/data"
username = "daffy"
password = "duck"
# workers = 2
# limit = 3

[[backends]]
name = "weather"
type = "csv"
rootDir = "/tmp"
